### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'embeddings/word2vec_swda_300dim.txt'

### ISSUE THREAD

**Issue by Huangliang0826** [NathanDuran/Probabilistic-RNN-DA-Classifier#2]
When I run the: "python generate_embeddings.py"

I got this error:

FileNotFoundError: [Errno 2] No such file or directory: 'embeddings/word2vec_swda_300dim.txt'

**Comment by NathanDuran** [comment]
Hi,

Sorry that file was in the .gitnore. I have now added it to the repository, so it should work. Note that you can also specify glove_Wiki_300dim.txt or word2vec_GoogleNews_300dim.bin as the embedding file. They are not included in the project to save space, but they are available to download and simply place them in the embeddings directory.
